### ISSUE TITLE
error happens in torchlib, when retraining the model

### ISSUE THREAD

**Issue by Minotaur-CN** [mgharbi/demosaicnet_torch#2]
Dear mgharbi，
Some error happens when using 'make train_demo', It seems some wrong using torchlib.
 self.vis = visdom.Visdom(port=port, env=env) the env is none，and not init correctly at __init__  .
I already start the visdom server by 'python -m visdom.server'

Thanks!

-----------------------------------

Traceback (most recent call last):
  File "\~/anaconda3/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "\~/anaconda3/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "\~/anaconda3/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "\~/Project/demosaicnet_torch-master/train.py", line 16, in <module>
    from torchlib.trainer import Trainer
  File "./torchlib/trainer.py", line 14, in <module>
    class Trainer(object):
  File "./torchlib/trainer.py", line 52, in Trainer
    callbacks=[callbacks.LossCallback()], valset=None,
  File "./torchlib/callbacks.py", line 28, in __init__
    "loss", opts={"legend": ["train", "val"]}, env=env)
  File "./torchlib/viz.py", line 12, in __init__
    super(ScalarVisualizer, self).__init__(port=port, env=env)
  File "./torchlib/viz.py", line 7, in __init__
    self.vis = visdom.Visdom(port=port, env=env)
  File "~/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 406, in __init__
    }, endpoint='env/' + env)
TypeError: must be str, not NoneType
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program

 ~/anaconda3/lib/python3.6/site-packages/visdom/__init__.py(406)__init__()
 }, endpoint='env/' + env)

**Comment by mgharbi** [comment]
ditto

**Comment by Minotaur-CN** [comment]
Thanks for your kindly reply!
^.^
