### ISSUE TITLE
ValueError: too many values to unpack?

### ISSUE THREAD

**Issue by Minotaur-CN** [mgharbi/demosaicnet_torch#4]
Dear mgharbi,
There had one error when run the 'make train_demo'. Following the the log.
Thanks for your help!

BR,

--------------------------------------------

out[idx, 0] = (arr[idx, 1] - arr[idx, 2]) / delta[idx]
[14753] INFO train.py:54 | Model configuration: {'model': 'BayerNetwork'}
[14753] INFO train.py:57 | Loading Caffe weights
[14753] INFO train.py:99 | Using l2 loss
Traceback (most recent call last):
  File "bin/train.py", line 190, in <module>
    main(args, params)
  File "bin/train.py", line 132, in main
    valset=val_data, cuda=True)
  File "/home//Project/demosaicnet_torch-master/torchlib/trainer.py", line 135, in __init__
    self._set_model()
  File "/home//Project/demosaicnet_torch-master/torchlib/trainer.py", line 213, in _set_model
    chkpt_name, epoch = self.checkpointer.load_latest()
ValueError: too many values to unpack (expected 2)
Makefile:180: recipe for target 'train_demo' failed
make: *** [train_demo] Error 1

**Comment by mgharbi** [comment]
ditto, I will not track the changes in torchlib.

**Comment by Minotaur-CN** [comment]
Thanks for your kindly reply!
^.^
